#!/usr/bin/env bash

TODO='# TODO:'

email=`git config user.email`

> todos/todos.tmp
# first cycle through python modules with todos
for file in `git grep -l "$TODO" | grep '\.py$'`; do
    # use git blame with options to ignore whitespace
    # changes and moves within files in commit
    echo "`git blame -f -e -wC "$file" | \
        # get todos from the commit
        grep "$TODO" | \
        # remove commit hash
        sed "s/.\{9\}//"  |  \
        # replace committer info with email
        sed "s/(.*\(\<.*\>\).*)/\1/" | \
        # switch first two columns
        awk '{ t = $1; $1 = $2; $2 = t; print; }'`" >> todos/todos.tmp
done

# format into markdown
./todos/aggregate_todos.py

# stage markdown output file
git add 'todos/README.md'

rm todos/todos.tmp
exit 0
