#!/usr/bin/env bash

# Register your pre-commit hooks here
# in the order you want them executed.
# They should be in the location:
# .git/hooks/pre_commit
hook_names = (
    'isort'
    'whitespace'
    'forbidden'
    'todo'
)

# if using virtualenv & virtualenvwrapper
# set your project name here
PROJECT_NAME=

if [ -n "$PROJECT_NAME" ]; then
    # Git will not understand the 'workon' command.
    # This assumes you source your virtualenvwrapper
    # script in bashrc
    if [ -z "$VIRTUAL_ENV" ]; then
        source ${HOME}/.bashrc
        workon ${PROJECT_NAME}
    fi
fi

# store exit code for each hook
# so we can echo any feedback instead of 
# failing immediately
exit_codes=()

for hook_name in "${hook_names[@]}"; do
    hook="./.git/hooks/pre_commit/$hook_name"
    if [ -x "$hook" ]; then
        "$hook"
        exit_codes+=($?)
    else
        echo "$hook_name is not executable."
        exit_codes+=(1)
        continue
    fi
done


for code in "${exit_codes[@]}"; do
  [ $code -eq 0 ] || exit $code
done

exit 0

